name = "megha-backend"
main = "src/server/index.ts"
compatibility_date = "2025-01-22"

compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true

[vars]
SECRET = "meghaexpressbackend"
ACCOUNTID = "a26a722bd6408842de8098dadebaebe3"
DATABASEID = "1bcd7691-54d4-4fee-b368-4c340a895021"
TOKEN = "oMmVhkIcI30vCQGRmAc1tMXKeMew8ZBgP6-AghgK"

[[d1_databases]]
binding = "DB"
database_name = "megha-backend"
database_id = "1bcd7691-54d4-4fee-b368-4c340a895021"
migrations_dir = "drizzle"
